config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  resources :donations

  resources :institutions
end

app/models/donation.rb
# -*- encoding : utf-8 -*-
class Donation < ActiveRecord::Base

  validates_presence_of :item

  belongs_to :institution
end

app/models/institution.rb
# -*- encoding : utf-8 -*-
class Institution < ActiveRecord::Base

  validates_presence_of :name, :item

  has_one :user, as: :role

  has_many :donations
  
  scope :search, ->(name = '') { where("name like ? or item like ?", "%#{name}%", "%#{name}%") }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role, polymorphic: true, dependent: :destroy
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
# -*- encoding : utf-8 -*-
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.where(donator_id: current_user.id)
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
    @items =[ ["Brinquedos","Brinquedos"],
              ["Roupas","Roupas"],
              ["Dinheiro","Dinheiro"],
              ["Alimentos", "Alimentos"]]
  end

  # GET /donations/1/edit
  def edit
    @items =[ ["Brinquedos","Brinquedos"],
              ["Roupas","Roupas"],
              ["Dinheiro","Dinheiro"],
              ["Alimentos", "Alimentos"]]
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Doação realizada com sucesso!' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Doação atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params[:donation].permit(:item, :quantity, :value, :date, :institution_id).merge(donator_id: current_user.id)
    end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  # GET /
  def index
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.search(params[:name])
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
    @items =[ ["Brinquedos","Brinquedos"],
              ["Roupas","Roupas"],
              ["Dinheiro","Dinheiro"],
              ["Alimentos", "Alimentos"]]
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :item)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
# -*- encoding : utf-8 -*-
module DonationsHelper
end

app/helpers/institutions_helper.rb
# -*- encoding : utf-8 -*-
module InstitutionsHelper
end

app/views/donations/_form.html.erb
<%= simple_form_for(@donation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :item, collection: @items,  label_method: :first, value_method: :last, input_html: { class: 'chosen-select',  data: { placeholder: "Selecione uma item" } } %>


    <%= f.input :quantity %>
    <%= f.input :date %>
    <%= f.input :value %>
    <%= f.association :institution %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h2>Minhas Doações</h2>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantidade</th>
      <th>Valor Financeiro</th>
      <th>Data</th>
      <th>Instituição</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%=donation.item%></td>
        <td><%=donation.quantity%></td>
        <td><%=donation.value%></td>
        <td><%=donation.date%></td>
        <td><%=link_to donation.institution.name, donation.institution %></td>
        <td><%= link_to 'Detalhes', donation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Doação', new_donation_path, class: "button" %>

app/views/donations/new.html.erb
<h1>Nova Doação</h1>

<div class= "small-6 small-centered collums">
  <%= render 'form' %>
</div>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<h2>Doação - Código: <%= @donation.id  %> </h2>

<strong>Item</strong>
<p>
  <%= @donation.item %>
</p>

<strong>Quantidade</strong>
<p>
  <%= @donation.quantity %>
</p>

<strong>Valor Financeiro</strong>
<p>
  <%= @donation.value %>
</p>

<strong>Data</strong>
<p>
  <%= @donation.date %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/home/index.html.erb
<div class="row">
  <h1 class="text-left">Doações</h1>
  <br>
  <div class="large-12 medium-2 columns">
    <h3 class="subheader text-center">
      Sistema de gerenciamento de doações para a disciplina de
      <br>
      Empreendedorismo do curso de Engenharia de Software da UFRN
    </h3>

    <%= simple_form_for :institution, :url => user_registration_path do |f| %>
      <div class="small-6 large-centered columns">
        <div class="row collapse">

          <%= f.email_field :email, :name => "user[email]", :type => "email", label: false, placeholder: "Email" %>
          <%= f.password_field :password, :name => "user[password]", label: false, placeholder: "Senha" %>
          <%= f.password_field :password_confirmation, :name => "user[password_confirmation]", label: false, placeholder: "Confirmação da Senha" %>
          <%= f.submit 'Join Us', class: "button postfix" %>
        </div>
      </div>

    <% end %>
    <form>

    </form>
  </div>
</div>

app/views/institutions/_form.html.erb
<%= simple_form_for(@institution) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :item, collection: @items,  label_method: :first, value_method: :last, input_html: { class: 'chosen-select',  data: { placeholder: "Selecione uma item" } } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h2>Instituições</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Item</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.item %></td>
        <td><%= link_to 'Detalhes', institution %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Intituição', new_institution_path, class: "button" %>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<h2>Intituição - <%= @institution.name %> </h2>

<p>
  <strong>Nome:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Recebe:</strong>
  <%= @institution.item %>
</p>

<hr>

<h3>Doações</h3>
<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantidade</th>
      <th>Valor Financeiro</th>
      <th>Data</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @institution.donations.each do |donation| %>
      <tr>
        <td><%=donation.item%></td>
        <td><%=donation.quantity%></td>
        <td><%=donation.value%></td>
        <td><%=donation.date%></td>
        <td><%= link_to 'Detalhes', donation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nova Doação', new_donation_path(@institution), class: "button" %>

<br>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Doações</title>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'vendor/modernizr', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Doações", root_url %></h1>
        </li>
        <li class="toggle-topbar menu-icon">
          <a href="#"><span>Menu</span></a>
        </li>
      </ul>
      <section class="top-bar-section"> <!-- Right Nav Section -->
        <ul class="left">
          <li><%= link_to "Minhas Doações", donations_path %></li>

          <li class="has-form">
            <form method="GET" action="<%= institutions_path %>">
              <div class="row collapse">
                <div class="large-8 small-9 columns">
                  <%= text_field_tag :name, params[:name], :placeholder => 'Instituições...' %>
                </div>
                <div class="large-4 small-3 columns">
                  <%= submit_tag "Buscar", :class => 'info button expand', :name => nil %>
                </div>
              </div>
            </form>
          </li>
          <li><%= link_to "Todas as Instituições", institutions_path %></li>
        </ul>
        <ul class="right">
          <li class="has-dropdown">
            <a href="javascript:;">Sessão <%= "(" + current_user.email + ")" if user_signed_in? %></a>
            <ul class="dropdown">
              <% if user_signed_in? %>
                <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Entrar", new_user_session_path %></li>
                <li><%= link_to "Criar Conta", new_user_registration_path %></li>
              <% end %>
            </ul>
          </li>
        </ul> <!-- Left Nav Section -->
      </section>
    </nav>
    <div class= "row">
      <div class="small-12 columns">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>

  </body>
</html>